[package]
name = "psci"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Andrew Walbran <qwandor@google.com>"]
keywords = ["arm", "aarch64", "cortex-a", "psci"]
categories = ["embedded", "no-std", "hardware-support"]

[features]
default = ["hvc"]
hvc = []
smc = []

[dependencies]
